# Generated by Django 4.2.29 on 2026-03-04 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=50)),
                ('level', models.PositiveIntegerField(default=1)),
                ('ability_scores', models.JSONField(default=dict)),
                ('skills', models.JSONField(default=list)),
                ('equipment', models.JSONField(default=list)),
                ('spells', models.JSONField(default=list)),
                ('background', models.CharField(blank=True, max_length=100)),
                ('hp', models.PositiveIntegerField(default=0)),
                ('character_data', models.JSONField(blank=True, default=dict)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='campaigns.campaign')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['name'], name='characters__name_6d8b81_idx'), models.Index(fields=['campaign'], name='characters__campaig_10ef48_idx'), models.Index(fields=['is_archived'], name='characters__is_arch_8e1592_idx'), models.Index(fields=['updated_at'], name='characters__updated_a40242_idx'), models.Index(fields=['owner'], name='characters__owner_i_cdb92a_idx')],
            },
        ),
    ]
