# Generated by Django 3.1.14 on 2026-03-04 15:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterShareToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_tokens', to='characters.character')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
